name = "spin-mama-bonus-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-bonus.com"
HMAC_KEY = "bfdc620a3d4ab975c66010836472f5922a1cebd8bf966570b9db42dd0752cb20"
COOKIE_NAME = "vmq"
PLAY_PATH = "visit"
BUTTON_ID = "pd673bf50a9908ccd1f3c44e929f4a86d"
GATE_SALT = "ca9d0259c9722acf"
